#!/bin/sh

pgrep -x dmenu -l 10 && exit

screen=$(xrandr | grep connected | dmenu -p "Choose Display" -l 10 | awk '{print $1}')

[[ $screen = "" ]] && exit 1

res=$(xrandr | dmenu -p "Choose resolution under selected display $screen" -l 10 | awk '{print $1}')

[[ $res = "" ]] && exit 1

exec setbg &

xrandr --output $screen --mode $res && echo | dmenu -p "Resolution changed."


